name: hashmap
on: push
jobs:
  check_job:
    name: check job
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: make
      run: mkdir build&&cd build&&cmake ..&&make